# Moyenne mobile en NumPy

La moyenne mobile sur fenêtre k consiste à remplacer chaque valeur par la moyenne des k valeurs précédentes (elle-même incluse).

Exemple avec k=3 sur [1, 2, 3, 4, 5] :
- position 2 : (1+2+3)/3 = 2.0
- position 3 : (2+3+4)/3 = 3.0
- position 4 : (3+4+5)/3 = 4.0

Les k-1 premières positions sont sans valeur.

In [62]:
import numpy as np

prices = np.array([100, 102, 101, 105, 110, 108, 112, 115, 113, 118])
prices_float = prices.astype(float)
print(prices)
print(prices_float)

[100 102 101 105 110 108 112 115 113 118]
[100. 102. 101. 105. 110. 108. 112. 115. 113. 118.]


In [63]:
def moving_average(arr: np.ndarray, window: int) -> np.ndarray:
    """Moyenne mobile sans boucle Python.

    Indice : utilise np.cumsum() pour calculer une somme cumulée,
    puis fais la différence entre deux positions pour obtenir la somme glissante.
    """
    prices_cumsum = np.cumsum(arr)
    prices_moving_avg = prices_cumsum.copy()

    for i in range(1 , len(arr) + 1):
        if  i - window - 1 < -1:
            prices_cumsum[i - 1] =  np.nan
        elif i - window - 1 < 0:
            prices_cumsum[i - 1] =  prices_cumsum[i - 1] / window
        else:
            prices_cumsum[i - 1] =  (prices_cumsum[i - 1] - prices_moving_avg[i - window - 1])/ window
    return prices_cumsum
        

# Test rapide
print(moving_average(prices_float, 3))

[         nan          nan 101.         102.66666667 105.33333333
 107.66666667 110.         111.66666667 113.33333333 115.33333333]


In [64]:
import pandas as pd
pd.Series(prices).rolling(3).mean().values

array([         nan,          nan, 101.        , 102.66666667,
       105.33333333, 107.66666667, 110.        , 111.66666667,
       113.33333333, 115.33333333])